const fs = require('fs');
const path = require('path');

const outDir = path.join(process.cwd(), 'out');
const indexHtml = path.join(outDir, 'index.html');
const enIndexHtml = path.join(outDir, 'en', 'index.html');
const noJekyllFile = path.join(outDir, '.nojekyll');

// With localePrefix: 'as-needed', the root page is already generated by Next.js
// We just need to ensure index.html exists (it should be created by Next.js)
// If it doesn't exist, copy from en/index.html as fallback
if (!fs.existsSync(outDir)) {
    console.error('Error: out directory does not exist. Run "yarn build" first.');
    process.exit(1);
}

// Create .nojekyll file to prevent GitHub Pages from ignoring _next directory
// Always create/update it to ensure it's present
fs.writeFileSync(noJekyllFile, '');
console.log('✓ Created/updated .nojekyll file to allow _next directory on GitHub Pages');

// Check if root index.html already exists (Next.js should create it)
if (fs.existsSync(indexHtml)) {
    console.log('✓ index.html already exists in out/ directory');
} else if (fs.existsSync(enIndexHtml)) {
    // Copy from en/index.html as fallback
    fs.copyFileSync(enIndexHtml, indexHtml);
    console.log('✓ Copied index.html from en/ to root');
} else {
    console.warn('⚠ Warning: Neither root index.html nor en/index.html found');
}

